version: '3.9'

services:
  angular:
    build: ./frontend
    ports:
      - 4200:4200
  node:
    build: ./backend
    ports:
      - 3000:3000
    environment:
      MONGO_URL: mongodb+srv://admin:oum6ZdhsYIFYEyuR@cluster0.5cmaqsn.mongodb.net/
